config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('mymap/', include('mymap.urls')),
    path('mychannel/', include('mychannel.urls')),
    path('', include('healthcheck.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

healthcheck/urls.py
from django.urls import path

from . import views


app_name = 'healthcheck'
urlpatterns = [
    path('', views.healthcheck, name='healthcheck'),
]

mychannel/urls.py
from django.urls import path
from . import views

app_name = 'mychannel'
urlpatterns = [
 path('', views.index, name='index'),
]

mymap/urls.py
from django.urls import path
from . import views

app_name = 'mymap'
urlpatterns = [
 path('', views.index, name='index'),
]

polls/urls.py
from django.urls import path

from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mychannel/models.py
from django.db import models

# Create your models here.

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now >= self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

routesearch/models.py
from django.db import models

# Create your models here.

healthcheck/views.py
import os
from django.http import HttpResponse


def healthcheck(request):
    hostname = os.uname()[1]
    return HttpResponse("Hello, from {}".format(hostname))

mychannel/views.py
from django.shortcuts import render
from django.http import HttpResponse
#from django. import
#import requests
#import json


# Create your views here.
def index(request):
    return render(request,'mychannel/mychannel_info.html')

mymap/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, 'mymap/mymap_info.html')

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            'polls/detail.html',
            {
                'question': question,
                'error_message': 'You did not select a choice.'
            }
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question_id, )))

routesearch/views.py
from django.shortcuts import render

# Create your views here.

polls/templates/mychannel/mychannel_info.html
<!DOCTYPE html>
<html lang=ja>
    <head>
        <meta charset="UTF-8">
        <title>ルート検索</title>
    </head>
    <body>
        <p>ルート検索結果</p>
        <img width="200" height="200" src="https://map.yahooapis.jp/course/V1/routeMap?appid=dj00aiZpPU9lQ0t1VU1VTGN3RCZzPWNvbnN1bWVyc2VjcmV0Jng9MDU-&route=35.68233286004894,139.76649043148458,35.685173782469064,139.76584670132092|color:0000ffff&width=200&height=200">
    </body>
</html>

polls/templates/mymap/mymap_info.html
<!DOCTYPE html>
<html>
<body>
<div id="map" style="width:400px; height:300px"></div>
 
<script type="text/javascript" charset="utf-8" src="https://map.yahooapis.jp/js/V1/jsapi?appid=dj00aiZpPU5BV0htQU40M1lqSyZzPWNvbnN1bWVyc2VjcmV0Jng9OGI-"></script>
<script src="https://map.yahooapis.jp/course/V1/routeMap?appid=dj00aiZpPU5BV0htQU40M1lqSyZzPWNvbnN1bWVyc2VjcmV0Jng9OGI-&route=35.68233286004894,139.76649043148458,35.685173782469064,139.76584670132092|color:0000ffff&width=200&height=200"></script>
<script type="text/javascript">
window.onload = function(){
   var ymap = new Y.Map("map");
   ymap.drawMap(new Y.LatLng(35.66572, 139.73100), 17, Y.LayerSetId.NORMAL);
}
 
</script>
</body>
</html>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>